language: node_js

os:
  - osx


node_js:
  - node
  - lts/*

install:
  - npm ci
  - npm -g install webpack-cli ts-node typescript webpack

cache:
  directories:
    - 'node_modules'

script:
  - npm test

notifications:
  email: false
