image: ubuntu
stack: node 10

cache:
  - node_modules

branches:
  only:
    - main
    - develop

install:
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test
